/* -*- Mode:C++; c-file-style:"gnu"; indent-tabs-mode:nil; -*- */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_named_data_ice_1ar_service_NfdService */

#ifndef _Included_net_named_data_ice_1ar_service_NfdService
#define _Included_net_named_data_ice_1ar_service_NfdService
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     net_named_data_ice_1ar_service_NfdService
 * Method:    test
 * Signature: (Ljava/lang/Map;)V
 */
JNIEXPORT void JNICALL
Java_net_named_1data_ice_1ar_NdnRtcWrapper_test(JNIEnv*, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
