/* -*- Mode:C++; c-file-style:"gnu"; indent-tabs-mode:nil; -*- */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_named_data_ice_1ar_service_NfdService */

#ifndef _Included_net_named_data_ice_1ar_service_NfdService
#define _Included_net_named_data_ice_1ar_service_NfdService
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     net_named_data_ice_1ar_NdnRtcWrapper
 * Method:    start
 * Signature: (Ljava/lang/Map;)V
 */
JNIEXPORT void JNICALL
Java_net_named_1data_ice_1ar_NdnRtcWrapper_start(JNIEnv*, jclass, jobject);

/*
 * Class:     net_named_data_ice_1ar_NdnRtcWrapper
 * Method:    stop
 * Signature: (Ljava/lang/Map;)V
 */
JNIEXPORT void JNICALL
Java_net_named_1data_ice_1ar_NdnRtcWrapper_stop(JNIEnv*, jclass);

JNIEXPORT void JNICALL
Java_net_named_1data_ice_1ar_NdnRtcWrapper_attach(JNIEnv* env, jclass, jobject logcat);

JNIEXPORT void JNICALL
Java_net_named_1data_ice_1ar_NdnRtcWrapper_detach(JNIEnv* env, jclass, jobject logcat);

#ifdef __cplusplus
}
#endif
#endif
